add Nguyen_HanhNong bot to the SOR lab
Summer-of-Rust/sor-lab-7-prisoners pull request #2
Opened 2022-06-27 15:57 UTC by Nguyen-HanhNong

pull request to setup Nguyen_HanhNong bot to the Summer of Rust lab

2022-06-28 17:43 UTC, AngelOnFira commented
Looks like CI is failing, you'll need to run `cargo fmt` and `cargo clippy` :) Also, I think you're going to need to change your struct name by removing the underscore. That should be fine I think :100:

2022-06-30 03:29 UTC, AngelOnFira requested changes
Just one small thing then this will be good to go :)

2022-06-30 03:29 UTC, AngelOnFira commented on src/bots/mod.rs
> +            Bots::NguyenHanhNong => Box::new(nguyen_hanh_nong::NguyenHanhNong::new()),
Can we change this to a use statement? At the top of the page, there are some examples of how this is done with the other bots :)

2022-06-30 16:18 UTC, Nguyen-HanhNong commented
accidentally deleted your comment, my bad. It kept appearing in vscode every time I tried to change the declaration at line 56 .

2022-07-02 03:23 UTC, AngelOnFira approved these changes

2022-07-02 03:40 UTC, merged